CREATE TABLE CATEGORIES
(
    ID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL
);

CREATE TABLE PRODUCT_STATUSES
(
    ID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL
);

CREATE TABLE PRODUCTS
(
    ID            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME          VARCHAR2(255)                           NOT NULL,
    DESCRIPTION   VARCHAR2(2000)                          NULL,
    CURRENT_PRICE FLOAT(2)                                NOT NULL,
    QUANTITY      NUMBER(10, 0)                           NOT NULL,
    STATUS_ID     NUMBER REFERENCES PRODUCT_STATUSES (ID) NOT NULL
);

CREATE TABLE PRODUCT_CATEGORIES
(
    PRODUCT_ID  NUMBER REFERENCES PRODUCTS (ID) ON DELETE CASCADE,
    CATEGORY_ID NUMBER REFERENCES CATEGORIES (ID) ON DELETE CASCADE,

    CONSTRAINT PK_PRODUCT_CATEGORY PRIMARY KEY (PRODUCT_ID, CATEGORY_ID)
);

CREATE TABLE ADDRESSES
(
    ID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CITY   VARCHAR2(255) NOT NULL,
    STREET VARCHAR2(255) NOT NULL
);

CREATE TABLE PAYMENT_SOURCES
(
    ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Added a CHECK constraint to ensure valid Czech bank account format:
    -- [optional 2-6 digit prefix -] 2-10 digit account number / 4 digit bank code
    ACCOUNT VARCHAR2(255) NOT NULL
        CONSTRAINT CHK_BANK_ACCOUNT
            CHECK (REGEXP_LIKE(ACCOUNT, '^([0-9]{2,6}-)?[0-9]{2,10}/[0-9]{4}$')),
    TYPE    VARCHAR2(255) NOT NULL
);

-- Vztah generalizace/specializace:
-- Implementováno pomocí strategie "Class Table" (Dvě samostatné tabulky).
-- Tabulka CUSTOMERS funguje jako supertyp (představuje jakéhokoliv návštěvníka/zákazníka).
-- https://medium.com/@artemkhrenov/table-inheritance-patterns-single-table-vs-class-table-vs-concrete-table-inheritance-1aec1d978de1
CREATE TABLE CUSTOMERS
(
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

-- Tabulka REGISTERED_CUSTOMERS funguje jako podtyp.
-- Sdílí primární klíč s tabulkou CUSTOMERS, který zde zároveň funguje jako cizí klíč (vazba 1:1).
-- Obsahuje specifické atributy pouze pro registrované zákazníky.
CREATE TABLE REGISTERED_CUSTOMERS
(
    CUSTOMER_ID       NUMBER PRIMARY KEY REFERENCES CUSTOMERS (ID),
    NAME              VARCHAR2(255)                          NOT NULL,
    EMAIL             VARCHAR2(255)                          NOT NULL,
    PHONE             VARCHAR2(255)                          NOT NULL,
    PASSWORD          VARCHAR2(255)                          NOT NULL,
    ADDRESS_ID        NUMBER REFERENCES ADDRESSES (ID)       NOT NULL,
    PAYMENT_SOURCE_ID NUMBER REFERENCES PAYMENT_SOURCES (ID) NOT NULL
);

CREATE TABLE PAYMENT_STATUSES
(
    ID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL
);

CREATE TABLE PAYMENTS
(
    ID             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TRANSACTION_ID VARCHAR2(255)                           NOT NULL,
    PRICE          DECIMAL(10, 2)                          NOT NULL,
    STATUS_ID      NUMBER REFERENCES PAYMENT_STATUSES (ID) NOT NULL,
    PAID_AT        TIMESTAMP                               NOT NULL
);

CREATE TABLE ORDER_STATUSES
(
    ID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL
);

CREATE TABLE ORDERS
(
    ID                     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CREATED_AT             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS_ID              NUMBER REFERENCES ORDER_STATUSES (ID)                NOT NULL,
    VAT                    DECIMAL(10, 2)                                       NOT NULL,
    REGISTERED_CUSTOMER_ID NUMBER REFERENCES REGISTERED_CUSTOMERS (CUSTOMER_ID) NOT NULL,
    PAYMENT_ID             NUMBER REFERENCES PAYMENTS (ID)
);

CREATE TABLE ORDER_ITEMS
(
    ID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PRICE    DECIMAL(10, 2),
    QUANTITY NUMBER(10, 0),
    ORDER_ID NUMBER REFERENCES ORDERS (ID)
);


-- ================ MOCK DATA INSERT ================

INSERT INTO CATEGORIES (NAME)
VALUES ('Klávesnoce');
INSERT INTO CATEGORIES (NAME)
VALUES ('Myší');
INSERT INTO CATEGORIES (NAME)
VALUES ('Notebooky');
INSERT INTO CATEGORIES (NAME)
VALUES ('Monitory');


INSERT INTO PRODUCT_STATUSES (NAME)
VALUES ('Na skladě');
INSERT INTO PRODUCT_STATUSES (NAME)
VALUES ('Vyprodáno');

INSERT INTO PRODUCTS (NAME, DESCRIPTION, CURRENT_PRICE, QUANTITY, STATUS_ID)
VALUES ('Keychron V6 Max',
        'Herní klávesnice - mechanický spínač Gateron Jupiter Red, bezdrátová, podsvícená, klasické (vysokoprofilové) klávesy, americká lokalizace kláves, bluetooth a radiofrekvenční připojení (2,4GHz), podpora qmk/via firmware, na Li-Pol (dobíjecí akumulátor) baterie, šedá a černá barva, rozměry 3,25 × 44,79 × 14,9 cm (V×Š×H) ',
        2990,
        30,
        1);

